### ISSUE TITLE
website todo

### ISSUE THREAD

**Issue by sdtaylor** [sdtaylor/GrassForecasts#10]
**backend**
- [x] automatic grid creation from phenograss data

**aesthetics**
- [x] display all scenarios, but as different colors. models dont need to be identified
- [x] better color for map
- [x] better colors for bar graph

**features**
- [x] anomalies instead of raw "cover" values

**figure download** using built in plotly graph.
- [ ] include USDA/ARS watermark
- [ ] include location somehow, lat lon probably not good enough

**documentation**
- [ ] some intro page or tab outlining the intention and usage

**other**
- [ ] setup simple feedback form for ESA
- [ ] drop unneeded plotly options in the upper right

**Comment by sdtaylor** [comment]
read over M. Kenneys guidelines for effective visual communication https://www.umdindicators.org/?page_id=1028

**Comment by sdtaylor** [comment]
Other potential web graphic engines

Plotly (used by dash already, underlying engine is D3)
Bokeh (uses plotly)
[Altair](https://altair-viz.github.io/index.html) (underlying engine is [vega](https://vega.github.io/vega/))

**Comment by sdtaylor** [comment]
good map example with layout and hover stuff

https://dash-gallery.plotly.host/dash-spatial-clustering/  
code: https://github.com/plotly/dash-sample-apps/blob/master/apps/dash-spatial-clustering/app.py
