### ISSUE TITLE
ESA2020 todo

### ISSUE THREAD

**Issue by sdtaylor** [sdtaylor/GrassForecasts#14]
- [x] finalize phenograss models
- [x] add about/info tab
- [x] add survey tab. "ESA2020 FeedBack"
- [x] add my twitter (probably in the about)
- [x] change page title/icon
- [x] drop debug output
- [ ] change hover text to ranges
- [x] fix temperature hover text
- [ ] put climatology years in about
